# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: build
  displayName: Build job
  # Define the steps for the build job here
  # ...

- job: create_tag
  displayName: Create Git tag
  dependsOn: build
  condition: succeeded()
  steps:
  - script: |
      git tag -a $(Build.BuildNumber) -m "Build passed for $(Build.SourceBranchName)"
      git push --tags
    displayName: Create and push Git tag

