trigger:
- master



jobs:
- job: create_tag
  displayName: Create Git tag
  steps:
  - checkout: self
    persistCredentials: true
  - script: |
          git config --global user.email "sayedcaptain70@gmail.com"
          git config --global user.name "sayed-sd"
          #      echo "machine github.com login $(PAT)" >> .git/credentials
          git tag -a $(Build.BuildNumber) -m "Build passed for $(Build.SourceBranchName)"
          #      git push --tags https://$(GIT_USERNAME):$(PAT)@github.com/sayed-sd/settigunta
          git push origin --tags
          git fetch --tags --depth=2
          latest_tag=$(git describe --abbrev=0)
          previous_tag=$(git describe --abbrev=0 HEAD^)
          echo "Latest tag: $latest_tag"
          echo "Previous tag: $previous_tag"
     # displayName: Create and push Git tag