trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - changelog.txt

jobs:
- job: create_tag
  displayName: Create Git tag
  steps:
  - checkout: self
    persistCredentials: true
  - template: create-tag-script-template.yml
    parameters:
      buildNumber: $(Build.BuildNumber)
