trigger:
  branches:
    include:
      - master

jobs:
- job: create_tag
  displayName: Create Git tag
  steps:
  - checkout: self
    persistCredentials: true
  - script: |
      git config --global user.email "sayedcaptain70@hp.com"
      git config --global user.name "sayed-sd"
      git tag -a $(Build.BuildNumber) -m "Build passed for $(Build.SourceBranchName)"
      git push origin --tags
      git fetch --tags
      tags=$(git tag)
      previous_tag=""
      for tag in $tags; do
        if [ "$tag" = "$(Build.BuildNumber)" ]; then
          break
        fi
        previous_tag=$tag
      done
      changelog=$(git log --pretty=format:"%h - %s (%an)%n$(git diff $previous_tag..$(Build.BuildNumber))")
      echo "$changelog" > changelog.txt
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'changelog.txt'
      artifactName: 'changelog'
