# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


jobs:
- job: create_tag
  displayName: Create Git tag
  steps:
  - script: |
      git pull
      git config --global user.email "sayedcaptain70@gmail.com"
      git config --global user.name "sayed-sd"
      echo "machine github.com login $(PAT)" >> .git/credentials
      git tag -a $(Build.BuildNumber) -m "Build passed for $(Build.SourceBranchName)"
      git commit -m "Tag Updated"
      git push --tags https://$(GIT_USERNAME):$(PAT)@github.com/sayed-sd/settigunta

    displayName: Create and push Git tag
