# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
  tags:
    include:
    - 'release-*'

pool:
  vmImage: windows-latest

jobs:
- job: A
  displayName: 'JobA'
  steps:
  . . .

# JobB only runs when the pipeline is triggered by the tags like as the format 'release-xxx'.
- job: B
  displayName: 'JobB'
  condition: contains(variables['Build.SourceBranch'], 'refs/tags/release-')
  steps:
  ...